## Opening 10000 UDP ports for RTPEngine
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: rtpengine
  labels:
    component: rtpengine
spec:
  selector:
    matchLabels:
      component: rtpengine
  template:
    metadata:
      name: rtpengine
      labels:
        component: rtpengine
    spec:
      # Here we make sure the pod starts on a single node
      nodeSelector:
        # cloud.google.com/gke-nodepool: rtpengine
        rtpengine: "true"
      hostNetwork: true
      containers:
        - name: rtpengine
          image: psanders/rtpengine:test
          env:
            #- name: PUBLIC_IP
            #  value: "40.68.127.4"
            - name: BIND_HTTP_PORT
              value: "5000"
            - name: LOG_LEVEL
              value: "7" 
            - name: PORT_MIN
              value: "30000"
            - name: PORT_MAX
              value: "31000"              
            - name: CLOUD
              value: azure
