name: publish to docker hub
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number'
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Publish
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: fonoster/rtpengine
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          workdir: .
          tags: "latest,${{ github.event.inputs.version }},3"
